package vector;
import javax.swing.JOptionPane;
/**
 *
 * @author Alfredo Gonzales Quiucha
 */
public class FormVector extends javax.swing.JFrame {
    CVector CV;
    public FormVector() {
        CV=new CVector();
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();
        label4 = new java.awt.Label();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jButton31 = new javax.swing.JButton();
        jButton32 = new javax.swing.JButton();
        jButton33 = new javax.swing.JButton();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        label1.setText("label1");

        label2.setText("label2");

        label3.setText("label3");

        label4.setText("label4");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(750, 500));
        setSize(new java.awt.Dimension(0, 0));
        getContentPane().setLayout(null);

        jLabel1.setBackground(new java.awt.Color(204, 255, 204));
        jLabel1.setFont(new java.awt.Font("Elephant", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setText("VECTOR");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(294, 22, 139, 29);

        jButton1.setBackground(new java.awt.Color(204, 255, 204));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 102, 102));
        jButton1.setText("COLOCAR CANTIDAD DE ELEMENTOS");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(10, 60, 225, 23);

        jButton2.setBackground(new java.awt.Color(204, 255, 204));
        jButton2.setForeground(new java.awt.Color(0, 153, 102));
        jButton2.setText("OBTENER CANTIDAD DE ELEMENTOS");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(241, 60, 225, 24);

        jButton3.setBackground(new java.awt.Color(204, 255, 204));
        jButton3.setForeground(new java.awt.Color(0, 153, 102));
        jButton3.setText("CARGAR EL VECTOR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(10, 89, 225, 24);

        jScrollPane1.setBackground(new java.awt.Color(204, 255, 204));

        jTable1.setForeground(new java.awt.Color(0, 102, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "VECTOR"
            }
        ));
        jTable1.setRequestFocusEnabled(false);
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(240, 120, 220, 238);

        jButton4.setBackground(new java.awt.Color(204, 255, 204));
        jButton4.setForeground(new java.awt.Color(0, 153, 102));
        jButton4.setText("MOSTRAR EL VECTOR");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(241, 89, 225, 24);

        jButton5.setBackground(new java.awt.Color(204, 255, 204));
        jButton5.setForeground(new java.awt.Color(0, 153, 102));
        jButton5.setText("SUMA DE ELEMENTOS DEL VECTOR");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(10, 118, 225, 24);

        jButton6.setBackground(new java.awt.Color(204, 255, 204));
        jButton6.setForeground(new java.awt.Color(0, 153, 102));
        jButton6.setText("SUMA DE ELEMENTOS POSITIVOS");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(10, 147, 225, 24);

        jButton7.setBackground(new java.awt.Color(204, 255, 204));
        jButton7.setForeground(new java.awt.Color(0, 153, 102));
        jButton7.setText("SUMA DE ELEMENTOS NEGATIVOS");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(10, 176, 225, 24);

        jButton8.setBackground(new java.awt.Color(204, 255, 204));
        jButton8.setForeground(new java.awt.Color(0, 153, 102));
        jButton8.setText("CONTAR ELEMENTOS PAR");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8);
        jButton8.setBounds(10, 205, 225, 24);

        jToggleButton1.setBackground(new java.awt.Color(204, 255, 204));
        jToggleButton1.setForeground(new java.awt.Color(0, 153, 102));
        jToggleButton1.setText("CONTAR ELEMENTOS IMPAR");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton1);
        jToggleButton1.setBounds(10, 234, 225, 24);

        jButton9.setBackground(new java.awt.Color(204, 255, 204));
        jButton9.setForeground(new java.awt.Color(0, 153, 102));
        jButton9.setText("ELIMINAR ULTIMO ELEMENTO");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9);
        jButton9.setBounds(472, 362, 225, 24);

        jButton10.setBackground(new java.awt.Color(204, 255, 204));
        jButton10.setForeground(new java.awt.Color(0, 153, 102));
        jButton10.setText("CONTAR Y SUMAR LOS PARES");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton10);
        jButton10.setBounds(10, 263, 225, 24);

        jButton11.setBackground(new java.awt.Color(204, 255, 204));
        jButton11.setForeground(new java.awt.Color(0, 153, 102));
        jButton11.setText("VACIAR VECTOR");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton11);
        jButton11.setBounds(472, 60, 225, 24);

        jButton12.setBackground(new java.awt.Color(204, 255, 204));
        jButton12.setForeground(new java.awt.Color(0, 153, 102));
        jButton12.setText("BUSQUEDA SECUENCIAL DE ELEM.");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton12);
        jButton12.setBounds(472, 205, 225, 24);

        jButton13.setBackground(new java.awt.Color(204, 255, 204));
        jButton13.setForeground(new java.awt.Color(0, 153, 102));
        jButton13.setText("BUSQUEDA BINARIA");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton13);
        jButton13.setBounds(472, 234, 225, 24);

        jButton14.setBackground(new java.awt.Color(204, 255, 204));
        jButton14.setForeground(new java.awt.Color(0, 153, 102));
        jButton14.setText("ORDENAMIENTO POR INTERCAMBIO");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton14);
        jButton14.setBounds(472, 147, 225, 24);

        jButton15.setBackground(new java.awt.Color(204, 255, 204));
        jButton15.setForeground(new java.awt.Color(0, 153, 102));
        jButton15.setText("ORDENAMIENTO POR SELECCION");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton15);
        jButton15.setBounds(472, 118, 225, 24);

        jButton16.setBackground(new java.awt.Color(204, 255, 204));
        jButton16.setForeground(new java.awt.Color(0, 153, 102));
        jButton16.setText("ORDENAMIENTO BURBUJA");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton16);
        jButton16.setBounds(472, 89, 225, 24);

        jButton17.setBackground(new java.awt.Color(204, 255, 204));
        jButton17.setForeground(new java.awt.Color(0, 153, 102));
        jButton17.setText("ORD INTER ASCENDENTE - SELEC DESCENDENTE");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton17);
        jButton17.setBounds(387, 391, 310, 24);

        jButton18.setBackground(new java.awt.Color(204, 255, 204));
        jButton18.setForeground(new java.awt.Color(255, 102, 0));
        jButton18.setText("ELIMINAR ELEMENTO CUALQUIERA");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton18);
        jButton18.setBounds(472, 321, 225, 24);

        jButton19.setBackground(new java.awt.Color(204, 255, 204));
        jButton19.setForeground(new java.awt.Color(0, 153, 102));
        jButton19.setText("CORTE CONTROL");
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton19);
        jButton19.setBounds(10, 292, 225, 24);

        jButton20.setBackground(new java.awt.Color(204, 255, 204));
        jButton20.setForeground(new java.awt.Color(0, 153, 102));
        jButton20.setText("BUSCADOR DEL ELEMENTO MODA");
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton20);
        jButton20.setBounds(472, 263, 225, 24);

        jButton21.setBackground(new java.awt.Color(204, 255, 204));
        jButton21.setForeground(new java.awt.Color(255, 102, 0));
        jButton21.setText("ELIMINADOR PURGA");
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton21);
        jButton21.setBounds(10, 321, 225, 24);

        jButton22.setBackground(new java.awt.Color(204, 255, 204));
        jButton22.setForeground(new java.awt.Color(0, 153, 102));
        jButton22.setText("INTERCAMBIAR ELEMENTOS");
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton22);
        jButton22.setBounds(472, 176, 225, 24);

        jButton23.setBackground(new java.awt.Color(204, 255, 204));
        jButton23.setForeground(new java.awt.Color(0, 153, 102));
        jButton23.setText("ORD INTER DESC- BURB ASCEND- SELEC DESC");
        jButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton23ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton23);
        jButton23.setBounds(10, 391, 323, 24);

        jButton24.setBackground(new java.awt.Color(204, 255, 204));
        jButton24.setForeground(new java.awt.Color(0, 153, 102));
        jButton24.setText("BUSCADOR DE ELEMENTO NO MODA");
        jButton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton24ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton24);
        jButton24.setBounds(472, 292, 225, 24);

        jButton25.setBackground(new java.awt.Color(204, 255, 204));
        jButton25.setForeground(new java.awt.Color(0, 153, 102));
        jButton25.setText("CARGAR NUMEROS ORDENADOS");
        jButton25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton25ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton25);
        jButton25.setBounds(241, 362, 225, 24);

        jButton26.setBackground(new java.awt.Color(204, 255, 204));
        jButton26.setForeground(new java.awt.Color(0, 153, 102));
        jButton26.setText("CARGA ALEATORIA");
        jButton26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton26ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton26);
        jButton26.setBounds(10, 362, 225, 24);

        jButton27.setText("Pract 1");
        jButton27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton27ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton27);
        jButton27.setBounds(10, 420, 95, 24);

        jButton28.setText("Pract 2");
        jButton28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton28ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton28);
        jButton28.setBounds(115, 420, 90, 24);

        jButton29.setText("Pract 3");
        jButton29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton29ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton29);
        jButton29.setBounds(215, 420, 84, 24);

        jButton30.setText("Pract 4");
        jButton30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton30ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton30);
        jButton30.setBounds(309, 420, 80, 24);

        jButton31.setText("Pract 5");
        jButton31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton31ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton31);
        jButton31.setBounds(395, 420, 79, 24);

        jButton32.setText("Pract 6");
        jButton32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton32ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton32);
        jButton32.setBounds(480, 420, 74, 24);

        jButton33.setBackground(new java.awt.Color(255, 204, 153));
        jButton33.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton33.setText("Salir");
        jButton33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton33ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton33);
        jButton33.setBounds(620, 420, 68, 27);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String Cad="";
        Cad=JOptionPane.showInputDialog("Introduzca Cantidad de Elementos para Vectores:");
        int aux=Integer.parseInt(Cad);
        
        CV.SetDim(aux);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int aux=CV.GetCantidad();
        JOptionPane.showMessageDialog(rootPane,"La Cantidad de Elementos en el Vector es = "+aux);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if (CV.GetDim()!=-1)
            CV.CargarVector();
        else
            JOptionPane.showMessageDialog(rootPane, "Coloque la cantidad de elementos para el VECTOR");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        //Limpiar la tabla visualmente
        this.limpiarTabla();
        
        //PARA MOSTRAR LOS ELEMENTOS DEL VECTOR
        int aux=0;
        for(int i=0;i<=CV.GetDim();i++)//utilizamos esto porque no existe en la clase y por lo tanto aqui lo generamos de nuevo
        {
            aux=CV.GetValor(i);
            jTable1.setValueAt(aux, i, 0);//muestra el VALOR,FILAS,COLUMNA en la tabla
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        int aux=CV.SumaElemV();
        JOptionPane.showMessageDialog(rootPane,"La suma de los elementos es = "+aux);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        int aux=CV.SumaElemPosi();
        JOptionPane.showMessageDialog(rootPane,"La suma de los Elementos Positivos es = "+aux);
                
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        int aux=CV.SumaElemNega();
        JOptionPane.showMessageDialog(rootPane,"La Suma de los Elementos Negativos es = "+aux);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        int aux=CV.ContElemPar();
        JOptionPane.showMessageDialog(rootPane,"La Cantidad de los Elementos Par es = "+aux);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
        int aux=CV.ContElemImpar();
        JOptionPane.showMessageDialog(rootPane,"La Cantidad de Elementos Impar es = "+aux);
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        CV.ContSumaElemPar();
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        this.limpiarTabla();
        CV.EliminarUltimoElem();
        this.mostrarElementosVector();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        //Antes de vaciar fisicamente borramos (mostramos vacio "") los datos que se muestra en el vector
        for(int i=0;i<=CV.GetDim();i++){
            jTable1.setValueAt("", i, 0);
        }
        //Vacia el vector Fisicamente
        CV.VaciarVector();
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        String Cad="";
        Cad=JOptionPane.showInputDialog("Que Elemento desea Buscar");
        int elem=Integer.parseInt(Cad);
        
        int aux=CV.BusquedaSecuencial(elem);
        if (aux==1)
        {
            JOptionPane.showMessageDialog(rootPane,"El Elemento Existe");
        }
        else
        {
            JOptionPane.showMessageDialog(rootPane,"El Elemento NO Existe");
        }
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
        String Cad="";
        Cad=JOptionPane.showInputDialog("Introduzca el elemento a Buscar:");
        int elem=Integer.parseInt(Cad);
        //para realizar la busqueda binaria primero se debe ordenar el vector
        CV.OrdIntercambio();
        int aux=CV.BusquedaBinaria(elem);
        if(aux==1)
        {
            JOptionPane.showMessageDialog(rootPane,"Existe");
        }
        else
        {
            JOptionPane.showMessageDialog(rootPane,"No Existe");
        }
        
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
        CV.OrdIntercambio();
        this.mostrarElementosVector();
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
        CV.OrdSeleccion();
        this.mostrarElementosVector();
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        // TODO add your handling code here:
        CV.OrdBurbuja();
        this.mostrarElementosVector();
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        // TODO add your handling code here:
        CV.OrdIntASCSelecDES();
        this.mostrarElementosVector();
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
            // TODO add your handling code here:
        String Cad="";
        Cad=JOptionPane.showInputDialog("Introduzca la Posicion del Elemento a Eliminar");
        int aux=Integer.parseInt(Cad);
        aux=aux-1;
        CV.EliminarElementoCualquiera(aux);
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        // TODO add your handling code here:
        CV.OrdBurbuja();
        CV.CorteControl();
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        // TODO add your handling code here:
        CV.OrdBurbuja();
        int aux=CV.Moda();
        JOptionPane.showMessageDialog(rootPane,"El elemento moda es = "+aux);
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        // TODO add your handling code here:
        this.limpiarTabla();
        CV.OrdIntercambio();
        CV.Purga();
        this.mostrarElementosVector();
    }//GEN-LAST:event_jButton21ActionPerformed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
        // TODO add your handling code here:
        this.limpiarTabla();
        
        String Cad="";
        Cad=JOptionPane.showInputDialog("Introduzca posA para Intercambiar");
        int posA=Integer.parseInt(Cad);
        posA=posA-1;
        
        Cad=JOptionPane.showInputDialog("Introduzca posB para Intercambiar");
        int posB=Integer.parseInt(Cad);
        posB=posB-1;
        
        CV.InterElementos(posA, posB);
        
        this.mostrarElementosVector();
    }//GEN-LAST:event_jButton22ActionPerformed

    private void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton23ActionPerformed
        // TODO add your handling code here:
        CV.OrdIntercDESCBurbASCSelecDESC();
        this.mostrarElementosVector();
    }//GEN-LAST:event_jButton23ActionPerformed

    private void jButton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton24ActionPerformed
        // TODO add your handling code here:
        CV.OrdBurbuja();
        int aux=CV.NoModa();
        JOptionPane.showMessageDialog(rootPane,"El elemento No Moda es = "+aux);
    }//GEN-LAST:event_jButton24ActionPerformed

    private void jButton25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton25ActionPerformed
        // Carga el Vector con numeros ordenados desde el 1
        if (CV.GetDim()!=-1)
            CV.CargarVecOrdenado();
        else
            JOptionPane.showMessageDialog(rootPane, "Coloque la cantidad de elementos para el VECTOR");
        
        //Muestra directamente ni bien presionemos el boton CARGARVECTORORDENADO
        int aux=0;
        for(int i=0;i<=CV.GetDim();i++){
            aux=CV.GetValor(i);
            jTable1.setValueAt(aux, i, 0);
        }
    }//GEN-LAST:event_jButton25ActionPerformed

    private void jButton26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton26ActionPerformed
        //Verifica si esta vacio para luego cargar
        if (CV.GetDim()!=-1)
            CV.CargarAleatoria();
        else
            JOptionPane.showMessageDialog(rootPane, "Coloque la cantidad de elementos para el VECTOR");
        
        
        //Muestra Inmediatamente presionando el boton CARGAALEATORIA
        int aux=0;
        for(int i=0;i<=CV.GetDim();i++)
        {
            aux=CV.GetValor(i);
            jTable1.setValueAt(aux, i, 0);
        }
    }//GEN-LAST:event_jButton26ActionPerformed

    private void jButton27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton27ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,"La suma es="+CV.sumaPrimYUltElem());
    }//GEN-LAST:event_jButton27ActionPerformed

    private void jButton28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton28ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "La suma es="+CV.sumaPrimerCentroUltimoElem());
    }//GEN-LAST:event_jButton28ActionPerformed

    private void jButton29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton29ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "La suma es="+CV.sumaMult3());
    }//GEN-LAST:event_jButton29ActionPerformed

    private void jButton30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton30ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "La suma es = "+CV.suma3en3());
    }//GEN-LAST:event_jButton30ActionPerformed

    private void jButton31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton31ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "La suma es= "+CV.sumaElemInterc());
        //JOptionPane.showMessageDialog(null, "La suma es= "+CV.sumaElemInterc2());
    }//GEN-LAST:event_jButton31ActionPerformed

    private void jButton32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton32ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "La suma es= "+CV.suma2en2());
    }//GEN-LAST:event_jButton32ActionPerformed

    private void jButton33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton33ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton33ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormVector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormVector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormVector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormVector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormVector().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JToggleButton jToggleButton1;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    // End of variables declaration//GEN-END:variables
    
    private void limpiarTabla(){
        for (int i = 0; i < jTable1.getRowCount(); i++) {
            jTable1.setValueAt("", i, 0);
        }
    }
    
    private void mostrarElementosVector(){
        int aux=0;
        for(int i=0;i<=CV.GetDim();i++)//utilizamos esto porque no existe en la clase y por lo tanto aqui lo generamos de nuevo
        {
            aux=CV.GetValor(i);
            jTable1.setValueAt(aux, i, 0);//muestra el VALOR,FILAS,COLUMNA en la tabla
        }
    }
}
