package vector;
import javax.swing.JOptionPane;
/**
 *
 * @author Alfredo Gonzales Quiucha
 */
public class FormVector extends javax.swing.JFrame {
    CVector CV;
    public FormVector() {
        CV=new CVector();
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();
        label4 = new java.awt.Label();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton33 = new javax.swing.JButton();
        jPanelConfiguracion = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jPanelCargarDatos = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jPanelSumaElementos = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jPanelOrdenamiento = new javax.swing.JPanel();
        jButton16 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jPanelBusquedas = new javax.swing.JPanel();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jPanelOperacionesExtra = new javax.swing.JPanel();
        jButton10 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        jButton22 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jPanelEliminacion = new javax.swing.JPanel();
        jButton21 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jPanelPracticas = new javax.swing.JPanel();
        jButton17 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jPanelPracticas2 = new javax.swing.JPanel();
        jButton27 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jButton31 = new javax.swing.JButton();
        jButton32 = new javax.swing.JButton();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        label1.setText("label1");

        label2.setText("label2");

        label3.setText("label3");

        label4.setText("label4");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(750, 500));
        setSize(new java.awt.Dimension(0, 0));

        jLabel1.setFont(new java.awt.Font("Elephant", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("VECTOR");

        jScrollPane1.setBackground(new java.awt.Color(204, 255, 204));

        jTable1.setForeground(new java.awt.Color(0, 102, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "VECTOR"
            }
        ));
        jTable1.setRequestFocusEnabled(false);
        jScrollPane1.setViewportView(jTable1);

        jButton33.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButton33.setText("Salir");
        jButton33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton33ActionPerformed(evt);
            }
        });

        jPanelConfiguracion.setBackground(new java.awt.Color(255, 204, 153));
        jPanelConfiguracion.setBorder(javax.swing.BorderFactory.createTitledBorder("Configuración"));
        jPanelConfiguracion.setLayout(null);

        jButton1.setBackground(new java.awt.Color(255, 153, 153));
        jButton1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButton1.setText("Colocar cantidad de elementos");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanelConfiguracion.add(jButton1);
        jButton1.setBounds(10, 20, 260, 27);

        jButton2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButton2.setText("Obtener cantidad de elementos");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanelConfiguracion.add(jButton2);
        jButton2.setBounds(10, 50, 260, 27);

        jButton4.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButton4.setText("Mostrar elementos");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanelConfiguracion.add(jButton4);
        jButton4.setBounds(10, 80, 260, 27);

        jButton11.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButton11.setText("Vaciar");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanelConfiguracion.add(jButton11);
        jButton11.setBounds(10, 110, 260, 27);

        jPanelCargarDatos.setBackground(new java.awt.Color(204, 255, 204));
        jPanelCargarDatos.setBorder(javax.swing.BorderFactory.createTitledBorder("Cargar datos"));
        jPanelCargarDatos.setLayout(null);

        jButton3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButton3.setText("Manual");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanelCargarDatos.add(jButton3);
        jButton3.setBounds(10, 20, 260, 27);

        jButton25.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButton25.setText("Números ordenados");
        jButton25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton25ActionPerformed(evt);
            }
        });
        jPanelCargarDatos.add(jButton25);
        jButton25.setBounds(10, 50, 260, 27);

        jButton26.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButton26.setText("Aleatorio");
        jButton26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton26ActionPerformed(evt);
            }
        });
        jPanelCargarDatos.add(jButton26);
        jButton26.setBounds(10, 80, 260, 27);

        jPanelSumaElementos.setBorder(javax.swing.BorderFactory.createTitledBorder("Suma de elementos"));
        jPanelSumaElementos.setLayout(null);

        jButton5.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButton5.setText("Todos los elementos");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanelSumaElementos.add(jButton5);
        jButton5.setBounds(10, 20, 180, 27);

        jButton6.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButton6.setText("Elementos positivos");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanelSumaElementos.add(jButton6);
        jButton6.setBounds(10, 50, 180, 27);

        jButton7.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButton7.setText("Elementos negativos");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanelSumaElementos.add(jButton7);
        jButton7.setBounds(10, 80, 180, 27);

        jPanelOrdenamiento.setBorder(javax.swing.BorderFactory.createTitledBorder("Ordenamiento de elementos"));
        jPanelOrdenamiento.setLayout(null);

        jButton16.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButton16.setText("Burbuja");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        jPanelOrdenamiento.add(jButton16);
        jButton16.setBounds(10, 20, 180, 27);

        jButton15.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButton15.setText("Por Selección");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        jPanelOrdenamiento.add(jButton15);
        jButton15.setBounds(10, 50, 180, 27);

        jButton14.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButton14.setText("Por Intercambio");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        jPanelOrdenamiento.add(jButton14);
        jButton14.setBounds(10, 80, 180, 27);

        jPanelBusquedas.setBorder(javax.swing.BorderFactory.createTitledBorder("Métodos de búsqueda"));
        jPanelBusquedas.setLayout(null);

        jButton12.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButton12.setText("Secuencial");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanelBusquedas.add(jButton12);
        jButton12.setBounds(10, 20, 180, 27);

        jButton13.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButton13.setText("Binaria");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanelBusquedas.add(jButton13);
        jButton13.setBounds(10, 50, 180, 27);

        jButton20.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButton20.setText("Elemento Moda");
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });
        jPanelBusquedas.add(jButton20);
        jButton20.setBounds(10, 80, 180, 27);

        jButton24.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButton24.setText("Elemento No Moda");
        jButton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton24ActionPerformed(evt);
            }
        });
        jPanelBusquedas.add(jButton24);
        jButton24.setBounds(10, 110, 180, 27);

        jPanelOperacionesExtra.setBorder(javax.swing.BorderFactory.createTitledBorder("Operaciones extra"));
        jPanelOperacionesExtra.setLayout(null);

        jButton10.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButton10.setText("Contar y sumar elementos pares");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanelOperacionesExtra.add(jButton10);
        jButton10.setBounds(10, 80, 260, 27);

        jButton8.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButton8.setText("Contar elementos par");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanelOperacionesExtra.add(jButton8);
        jButton8.setBounds(10, 20, 260, 27);

        jToggleButton1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jToggleButton1.setText("Contrar elementos impares");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        jPanelOperacionesExtra.add(jToggleButton1);
        jToggleButton1.setBounds(10, 50, 260, 27);

        jButton22.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButton22.setText("Intercambiar elementos");
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });
        jPanelOperacionesExtra.add(jButton22);
        jButton22.setBounds(10, 110, 260, 27);

        jButton19.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButton19.setText("Corte Control");
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        jPanelOperacionesExtra.add(jButton19);
        jButton19.setBounds(10, 140, 260, 27);

        jPanelEliminacion.setBorder(javax.swing.BorderFactory.createTitledBorder("Eliminación de elementos"));
        jPanelEliminacion.setLayout(null);

        jButton21.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButton21.setText("Eliminador Purga");
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });
        jPanelEliminacion.add(jButton21);
        jButton21.setBounds(10, 20, 260, 27);

        jButton18.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButton18.setText("Eliminar Elemento Cualquiera");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        jPanelEliminacion.add(jButton18);
        jButton18.setBounds(10, 50, 260, 27);

        jButton9.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButton9.setText("Eliminar último elemento");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanelEliminacion.add(jButton9);
        jButton9.setBounds(10, 80, 260, 27);

        jPanelPracticas.setBorder(javax.swing.BorderFactory.createTitledBorder("Prácticas extra 1"));
        jPanelPracticas.setLayout(null);

        jButton17.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButton17.setText("Ordenar: Interc. Asc. - Selecc. Desc.");
        jButton17.setToolTipText("Ordenar el vector en dos partes:\nPrimer parte por ordenamiento Intercambio en forma Ascendente.\nSegunda parte por ordenamiento Selección en forma Descendente.");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        jPanelPracticas.add(jButton17);
        jButton17.setBounds(10, 20, 260, 27);

        jButton23.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButton23.setText("Ordenar: Interc.Desc.-Burb.Asc.-Selecc.Desc");
        jButton23.setToolTipText("Ordenar los elementos del vector: \nPrimera parte con Intercambio Descendente.\nSegunda parte con Burbuja Ascendente.\nTercera parte con Seleccion Descendente.");
        jButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton23ActionPerformed(evt);
            }
        });
        jPanelPracticas.add(jButton23);
        jButton23.setBounds(10, 50, 260, 27);

        jPanelPracticas2.setBorder(javax.swing.BorderFactory.createTitledBorder("Prácticas extra 2"));

        jButton27.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButton27.setText("Pract 1");
        jButton27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton27ActionPerformed(evt);
            }
        });
        jPanelPracticas2.add(jButton27);

        jButton28.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButton28.setText("Pract 2");
        jButton28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton28ActionPerformed(evt);
            }
        });
        jPanelPracticas2.add(jButton28);

        jButton29.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButton29.setText("Pract 3");
        jButton29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton29ActionPerformed(evt);
            }
        });
        jPanelPracticas2.add(jButton29);

        jButton30.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButton30.setText("Pract 4");
        jButton30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton30ActionPerformed(evt);
            }
        });
        jPanelPracticas2.add(jButton30);

        jButton31.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButton31.setText("Pract 5");
        jButton31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton31ActionPerformed(evt);
            }
        });
        jPanelPracticas2.add(jButton31);

        jButton32.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButton32.setText("Pract 6");
        jButton32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton32ActionPerformed(evt);
            }
        });
        jPanelPracticas2.add(jButton32);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 990, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelConfiguracion, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelCargarDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelPracticas2, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelSumaElementos, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelOrdenamiento, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelBusquedas, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelOperacionesExtra, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelEliminacion, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelPracticas, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(layout.createSequentialGroup()
                .addGap(910, 910, 910)
                .addComponent(jButton33))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelConfiguracion, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jPanelCargarDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jPanelPracticas2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelSumaElementos, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jPanelOrdenamiento, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jPanelBusquedas, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelOperacionesExtra, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jPanelEliminacion, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jPanelPracticas, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20)
                .addComponent(jButton33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String Cad="";
        Cad=JOptionPane.showInputDialog("Introduzca Cantidad de Elementos para Vectores:");
        int aux=Integer.parseInt(Cad);
        
        CV.SetDim(aux);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int aux=CV.GetCantidad();
        JOptionPane.showMessageDialog(rootPane,"La Cantidad de Elementos en el Vector es = "+aux);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        //Limpiar la tabla visualmente
        this.limpiarTabla();
        
        //PARA MOSTRAR LOS ELEMENTOS DEL VECTOR
        int aux=0;
        for(int i=0;i<=CV.GetDim();i++)//utilizamos esto porque no existe en la clase y por lo tanto aqui lo generamos de nuevo
        {
            aux=CV.GetValor(i);
            jTable1.setValueAt(aux, i, 0);//muestra el VALOR,FILAS,COLUMNA en la tabla
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        int aux=CV.SumaElemV();
        JOptionPane.showMessageDialog(rootPane,"La suma de los elementos es = "+aux);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        int aux=CV.SumaElemPosi();
        JOptionPane.showMessageDialog(rootPane,"La suma de los Elementos Positivos es = "+aux);
                
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        int aux=CV.SumaElemNega();
        JOptionPane.showMessageDialog(rootPane,"La Suma de los Elementos Negativos es = "+aux);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        int aux=CV.ContElemPar();
        JOptionPane.showMessageDialog(rootPane,"La Cantidad de los Elementos Par es = "+aux);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
        int aux=CV.ContElemImpar();
        JOptionPane.showMessageDialog(rootPane,"La Cantidad de Elementos Impar es = "+aux);
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        CV.ContSumaElemPar();
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        this.limpiarTabla();
        CV.EliminarUltimoElem();
        this.mostrarElementosVector();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        //Antes de vaciar fisicamente borramos (mostramos vacio "") los datos que se muestra en el vector
        for(int i=0;i<=CV.GetDim();i++){
            jTable1.setValueAt("", i, 0);
        }
        //Vacia el vector Fisicamente
        CV.VaciarVector();
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        String Cad="";
        Cad=JOptionPane.showInputDialog("Que Elemento desea Buscar");
        int elem=Integer.parseInt(Cad);
        
        int aux=CV.BusquedaSecuencial(elem);
        if (aux==1)
        {
            JOptionPane.showMessageDialog(rootPane,"El Elemento Existe");
        }
        else
        {
            JOptionPane.showMessageDialog(rootPane,"El Elemento NO Existe");
        }
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
        String Cad="";
        Cad=JOptionPane.showInputDialog("Introduzca el elemento a Buscar:");
        int elem=Integer.parseInt(Cad);
        //para realizar la busqueda binaria primero se debe ordenar el vector
        CV.OrdIntercambio();
        int aux=CV.BusquedaBinaria(elem);
        if(aux==1)
        {
            JOptionPane.showMessageDialog(rootPane,"Existe");
        }
        else
        {
            JOptionPane.showMessageDialog(rootPane,"No Existe");
        }
        
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
        CV.OrdIntercambio();
        this.mostrarElementosVector();
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
        CV.OrdSeleccion();
        this.mostrarElementosVector();
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        // TODO add your handling code here:
        CV.OrdBurbuja();
        this.mostrarElementosVector();
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        // TODO add your handling code here:
        CV.OrdIntASCSelecDES();
        this.mostrarElementosVector();
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
            // TODO add your handling code here:
        String Cad="";
        Cad=JOptionPane.showInputDialog("Introduzca la Posicion del Elemento a Eliminar");
        int aux=Integer.parseInt(Cad);
        aux=aux-1;
        CV.EliminarElementoCualquiera(aux);
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        // TODO add your handling code here:
        CV.OrdBurbuja();
        CV.CorteControl();
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        // TODO add your handling code here:
        CV.OrdBurbuja();
        int aux=CV.Moda();
        JOptionPane.showMessageDialog(rootPane,"El elemento moda es = "+aux);
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        // TODO add your handling code here:
        this.limpiarTabla();
        CV.OrdIntercambio();
        CV.Purga();
        this.mostrarElementosVector();
    }//GEN-LAST:event_jButton21ActionPerformed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
        // TODO add your handling code here:
        this.limpiarTabla();
        
        String Cad="";
        Cad=JOptionPane.showInputDialog("Introduzca posA para Intercambiar");
        int posA=Integer.parseInt(Cad);
        posA=posA-1;
        
        Cad=JOptionPane.showInputDialog("Introduzca posB para Intercambiar");
        int posB=Integer.parseInt(Cad);
        posB=posB-1;
        
        CV.InterElementos(posA, posB);
        
        this.mostrarElementosVector();
    }//GEN-LAST:event_jButton22ActionPerformed

    private void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton23ActionPerformed
        // TODO add your handling code here:
        CV.OrdIntercDESCBurbASCSelecDESC();
        this.mostrarElementosVector();
    }//GEN-LAST:event_jButton23ActionPerformed

    private void jButton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton24ActionPerformed
        // TODO add your handling code here:
        CV.OrdBurbuja();
        int aux=CV.NoModa();
        JOptionPane.showMessageDialog(rootPane,"El elemento No Moda es = "+aux);
    }//GEN-LAST:event_jButton24ActionPerformed

    private void jButton27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton27ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,"La suma es="+CV.sumaPrimYUltElem());
    }//GEN-LAST:event_jButton27ActionPerformed

    private void jButton28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton28ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "La suma es="+CV.sumaPrimerCentroUltimoElem());
    }//GEN-LAST:event_jButton28ActionPerformed

    private void jButton29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton29ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "La suma es="+CV.sumaMult3());
    }//GEN-LAST:event_jButton29ActionPerformed

    private void jButton30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton30ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "La suma es = "+CV.suma3en3());
    }//GEN-LAST:event_jButton30ActionPerformed

    private void jButton31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton31ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "La suma es= "+CV.sumaElemInterc());
        //JOptionPane.showMessageDialog(null, "La suma es= "+CV.sumaElemInterc2());
    }//GEN-LAST:event_jButton31ActionPerformed

    private void jButton32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton32ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "La suma es= "+CV.suma2en2());
    }//GEN-LAST:event_jButton32ActionPerformed

    private void jButton33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton33ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton33ActionPerformed

    private void jButton26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton26ActionPerformed
        //Verifica si esta vacio para luego cargar
        if (CV.GetDim()!=-1)
        CV.CargarAleatoria();
        else
        JOptionPane.showMessageDialog(rootPane, "Coloque la cantidad de elementos para el VECTOR");

        //Muestra Inmediatamente presionando el boton CARGAALEATORIA
        int aux=0;
        for(int i=0;i<=CV.GetDim();i++)
        {
            aux=CV.GetValor(i);
            jTable1.setValueAt(aux, i, 0);
        }
    }//GEN-LAST:event_jButton26ActionPerformed

    private void jButton25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton25ActionPerformed
        // Carga el Vector con numeros ordenados desde el 1
        if (CV.GetDim()!=-1)
        CV.CargarVecOrdenado();
        else
        JOptionPane.showMessageDialog(rootPane, "Coloque la cantidad de elementos para el VECTOR");

        //Muestra directamente ni bien presionemos el boton CARGARVECTORORDENADO
        int aux=0;
        for(int i=0;i<=CV.GetDim();i++){
            aux=CV.GetValor(i);
            jTable1.setValueAt(aux, i, 0);
        }
    }//GEN-LAST:event_jButton25ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if (CV.GetDim()!=-1)
        CV.CargarVector();
        else
        JOptionPane.showMessageDialog(rootPane, "Coloque la cantidad de elementos para el VECTOR");
    }//GEN-LAST:event_jButton3ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormVector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormVector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormVector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormVector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormVector().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanelBusquedas;
    private javax.swing.JPanel jPanelCargarDatos;
    private javax.swing.JPanel jPanelConfiguracion;
    private javax.swing.JPanel jPanelEliminacion;
    private javax.swing.JPanel jPanelOperacionesExtra;
    private javax.swing.JPanel jPanelOrdenamiento;
    private javax.swing.JPanel jPanelPracticas;
    private javax.swing.JPanel jPanelPracticas2;
    private javax.swing.JPanel jPanelSumaElementos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JToggleButton jToggleButton1;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    // End of variables declaration//GEN-END:variables
    
    private void limpiarTabla(){
        for (int i = 0; i < jTable1.getRowCount(); i++) {
            jTable1.setValueAt("", i, 0);
        }
    }
    
    private void mostrarElementosVector(){
        int aux=0;
        for(int i=0;i<=CV.GetDim();i++)//utilizamos esto porque no existe en la clase y por lo tanto aqui lo generamos de nuevo
        {
            aux=CV.GetValor(i);
            jTable1.setValueAt(aux, i, 0);//muestra el VALOR,FILAS,COLUMNA en la tabla
        }
    }
}
